default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: postgres

development:
  primary:
      <<: *default
      database: db/development.sqlite

production:
  <<: *default
  database: library
